<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.16.0.0</Version>
    <AssemblyVersion>0.16.0.0</AssemblyVersion>
    <FileVersion>0.16.0.0</FileVersion>
    <Copyright>Copyright © Perfare 2018-2022; Copyright © hozuki 2020</Copyright>
    <DebugType>embedded</DebugType>
    <PlatformTarget>x64</PlatformTarget>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetStudioFBXNative\AssetStudioFBXNative.vcxproj" />
    <ProjectReference Include="..\AssetStudio\AssetStudio.csproj" />
  </ItemGroup>

</Project>
